# Generated by Django 2.2.10 on 2020-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('propertType', models.TextField()),
                ('targetSale', models.TextField()),
                ('SoonTime', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='namephoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='sellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('propertType', models.TextField()),
                ('targetSale', models.TextField()),
                ('SoonTime', models.TextField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
